language: python
python:
  - "3.8"
before_install:
  - cd ..
  - git clone --depth=1 --branch=alpha https://github.com/UsergeTeam/Userge.git Userge
  - mv Userge-Plugins/plugins/ Userge/userge/plugins/unof_plugins/
  - cp -r Userge-Plugins/resources/* Userge/resources/
install:
  - pip install -r Userge/requirements.txt
  - pip install -r Userge-Plugins/requirements.txt
before_script:
  - rm -rf Userge-Plugins/
  - cd Userge
  - mkdir -p logs
script:
  - python -m tests
